lmsextreg/Pages/Approvals/Edit.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

using lmsextreg.Data;
using lmsextreg.Models;

namespace lmsextreg.Pages.Approvals
{
    [Authorize(Roles = "APPROVER")]
    public class EditModel: PageModel
    {
         private readonly ApplicationDbContext _dbContext;
         private readonly UserManager<ApplicationUser> _userManager;

        public EditModel(lmsextreg.Data.ApplicationDbContext dbCntx, UserManager<ApplicationUser> usrMgr)
        {
            _dbContext = dbCntx;
            _userManager = usrMgr;
        }         

        [BindProperty]
        public ProgramEnrollment ProgramEnrollment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ////////////////////////////////////////////////////////////
            // Step #1:
            // Check to see if records exists
            ////////////////////////////////////////////////////////////
            ProgramEnrollment = await _dbContext.ProgramEnrollments
                              .Where(pe => pe.ProgramEnrollmentID == id) 
                              .SingleOrDefaultAsync();     

            ////////////////////////////////////////////////////////////
            // Return "Not Found" if record doesn't exist
            ////////////////////////////////////////////////////////////
            if (ProgramEnrollment == null)
            {
                return NotFound();
            }                                     

            ////////////////////////////////////////////////////////////
            // Step #2:
            // Now that record exists, make sure that the logged-in user
            // is authorized to edit (approver/deny) enrollment
            // applications for this particular LMS Program.
            ////////////////////////////////////////////////////////////
            var sql = " SELECT * FROM public.\"ProgramEnrollment\" "
                    + "  WHERE  \"ProgramEnrollmentID\" = {0} "
                    + "    AND  \"LMSProgramID\" " 
                    + "     IN "
                    + "      ( "
                    + "        SELECT \"LMSProgramID\" "
                    + "          FROM public.\"ProgramApprover\" "
                    + "         WHERE \"ApproverUserId\" = {1} "
                    + "      ) ";

            ProgramEnrollment = null;
            ProgramEnrollment = await _dbContext.ProgramEnrollments
                                .FromSql(sql, id, _userManager.GetUserId(User))
                                .Include(pe => pe.LMSProgram)
                                .Include(pe => pe.Student)
                                    .ThenInclude(s => s.SubAgency)
                                    .ThenInclude(sa => sa.Agency)
                                .Include(pe => pe.EnrollmentStatus)
                                .SingleOrDefaultAsync();

            /////////////////////////////////////////////////////////////
            // We already know that record exists from Step #1 so if we
            // get a "Not Found" in Step #2, we know it's because the 
            // logged-in user is not authorized to edit (approve/deny)
            // enrollment applications for this LMS Program.
            /////////////////////////////////////////////////////////////
            if (ProgramEnrollment == null)
            {
                return Unauthorized();
            }
            
            return Page();                              
        }

        public async Task<IActionResult> OnPostAsync(int id, string status)
        {
            Console.WriteLine("Approvals.Edit.OnPost(): BEGIN");
            Console.WriteLine("id: " + id);
            Console.WriteLine("status: " + status);

            ////////////////////////////////////////////////////////////
            // Step #1:
            // Check to see if records exists
            ////////////////////////////////////////////////////////////
            ProgramEnrollment = await _dbContext.ProgramEnrollments
                              .Where(pe => pe.ProgramEnrollmentID == id) 
                              .SingleOrDefaultAsync();     

            ////////////////////////////////////////////////////////////
            // Return "Not Found" if record doesn't exist
            ////////////////////////////////////////////////////////////
            if (ProgramEnrollment == null)
            {
                Console.WriteLine("ProgramEnrollment NOT FOUND in Step# 1");
                return NotFound();
            } 

            ////////////////////////////////////////////////////////////
            // Step #2:
            // Now that record exists, make sure that the logged-in user
            // is authorized to edit (approver/deny) enrollment
            // applications for this particular LMS Program.
            ////////////////////////////////////////////////////////////
            var sql = " SELECT * FROM public.\"ProgramEnrollment\" "
                    + "  WHERE  \"ProgramEnrollmentID\" = {0} "
                    + "    AND  \"LMSProgramID\" " 
                    + "     IN "
                    + "      ( "
                    + "        SELECT \"LMSProgramID\" "
                    + "          FROM public.\"ProgramApprover\" "
                    + "         WHERE \"ApproverUserId\" = {1} "
                    + "      ) ";

            ProgramEnrollment = null;
            ProgramEnrollment = await _dbContext.ProgramEnrollments
                                .FromSql(sql, id, _userManager.GetUserId(User))
                                .SingleOrDefaultAsync();

            /////////////////////////////////////////////////////////////
            // We already know that record exists from Step #1 so if we
            // get a "Not Found" in Step #2, we know it's because the 
            // logged-in user is not authorized to edit (approve/deny)
            // enrollment applications for this LMS Program.
            /////////////////////////////////////////////////////////////
            if (ProgramEnrollment == null)
            {
                return Unauthorized();
            }            

            /////////////////////////////////////////////////////////////////
            // Update ProgramEnrollment Record
            /////////////////////////////////////////////////////////////////
            ProgramEnrollment.StatusCode = status;
            ProgramEnrollment.ApproverUserId = _userManager.GetUserId(User);
            _dbContext.ProgramEnrollments.Update(ProgramEnrollment);
            await _dbContext.SaveChangesAsync();

            /////////////////////////////////////////////////////////////////
            // Redirect to Approval Index Page
            /////////////////////////////////////////////////////////////////
            return RedirectToPage("./Index");          
        }
    }
}

lmsextreg/Pages/Approvals/Review.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using lmsextreg.Constants;
using lmsextreg.Data;
using lmsextreg.Models;
using lmsextreg.Services;

namespace lmsextreg.Pages.Approvals
{
    [Authorize(Roles = "APPROVER")]
    public class ReviewModel: PageModel
    {
         private readonly ApplicationDbContext _dbContext;
         private readonly UserManager<ApplicationUser> _userManager;
         private readonly IEmailSender _emailSender;

        public ReviewModel  (
                                lmsextreg.Data.ApplicationDbContext dbCntx, 
                                UserManager<ApplicationUser> usrMgr,
                                IEmailSender emailSndr
                            )
        {
            _dbContext = dbCntx;
            _userManager = usrMgr;
            _emailSender = emailSndr;
        }         

        public class InputModel
        {
            [Display(Name = "Remarks")]  
            public string Remarks { get; set; }
        }   


        [BindProperty]
        public InputModel Input { get; set; }
        public ProgramEnrollment ProgramEnrollment { get; set; }
        public IList<EnrollmentHistory> EnrollmentHistory { get;set; }
        public bool ShowReviewForm { get; set; }
        public bool ShowApproveButton {get; set; }
        public bool ShowDenyButton {get; set; }
        public bool ShowRevokeButton {get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ////////////////////////////////////////////////////////////
            // Step #1:
            // Check to see if records exists
            ////////////////////////////////////////////////////////////
            ProgramEnrollment = await _dbContext.ProgramEnrollments
                              .Where(pe => pe.ProgramEnrollmentID == id) 
                              .SingleOrDefaultAsync();     

            ////////////////////////////////////////////////////////////
            // Return "Not Found" if record doesn't exist
            ////////////////////////////////////////////////////////////
            if (ProgramEnrollment == null)
            {
                return NotFound();
            }                                     

            ////////////////////////////////////////////////////////////
            // Step #2:
            // Now that record exists, make sure that the logged-in user
            // is authorized to edit (approver/deny) enrollment
            // applications for this particular LMS Program.
            ////////////////////////////////////////////////////////////
            var sql = " SELECT * "
                    + "   FROM " + MiscConstants.DB_SCHEMA_NAME + ".\"ProgramEnrollment\" "
                    + "  WHERE  \"ProgramEnrollmentID\" = {0} "
                    + "    AND  \"LMSProgramID\" " 
                    + "     IN "
                    + "      ( "
                    + "        SELECT \"LMSProgramID\" "
                    + "          FROM " + MiscConstants.DB_SCHEMA_NAME + ".\"ProgramApprover\" "
                    + "         WHERE \"ApproverUserId\" = {1} "
                    + "      ) ";

            ProgramEnrollment = null;
            ProgramEnrollment = await _dbContext.ProgramEnrollments
                                .FromSql(sql, id, _userManager.GetUserId(User))
                                .Include(pe => pe.LMSProgram)
                                .Include(pe => pe.Student)
                                    .ThenInclude(s => s.SubAgency)
                                    .ThenInclude(sa => sa.Agency)
                                .Include(pe => pe.EnrollmentStatus)
                                .SingleOrDefaultAsync();

            EnrollmentHistory = await _dbContext.EnrollmentHistories
                                    .Where(eh => eh.ProgramEnrollmentID == ProgramEnrollment.ProgramEnrollmentID)
                                    .Include(eh => eh.Actor)
                                    .Include(eh => eh.StatusTransition)
                                    .OrderBy(eh => eh.EnrollmentHistoryID)
                                    .ToListAsync();
                                    
            /////////////////////////////////////////////////////////////
            // We already know that record exists from Step #1 so if we
            // get a "Not Found" in Step #2, we know it's because the 
            // logged-in user is not authorized to edit (approve/deny)
            // enrollment applications for this LMS Program.
            /////////////////////////////////////////////////////////////
            if (ProgramEnrollment == null)
            {
                return Unauthorized();
            }

            if ( ProgramEnrollment.StatusCode == StatusCodeConstants.PENDING )
            {
                ShowReviewForm      = true;
                ShowApproveButton   = true;
                ShowDenyButton      = true;
                ShowRevokeButton    = false;
            }
            if ( ProgramEnrollment.StatusCode == StatusCodeConstants.APPROVED )
            {
                ShowReviewForm      = true;
                ShowApproveButton   = false;
                ShowDenyButton      = false;
                ShowRevokeButton    = true;
            }   
            if ( ProgramEnrollment.StatusCode == StatusCodeConstants.DENIED )
            {
                ShowReviewForm      = true;
                ShowApproveButton   = true;
                ShowDenyButton      = false;
                ShowRevokeButton    = false;
            }   
            if ( ProgramEnrollment.StatusCode == StatusCodeConstants.REVOKED )
            {
                ShowReviewForm      = false;
                ShowApproveButton   = false;
                ShowDenyButton      = false;
                ShowRevokeButton    = false;
            }                                    

            return Page();                              
        }

        public async Task<IActionResult> OnPostApproveAsync(int id)
        {
            return await this.OnPostAsync
            (
                id, 
                StatusCodeConstants.APPROVED, 
                TransitionCodeConstants.PENDING_TO_APPROVED
            );
        }

        public async Task<IActionResult> OnPostDenyAsync(int id)
        {
            ///////////////////////////////////////////////////////////////
            // Remarks are required when Enrollment Request is DENIED
            ///////////////////////////////////////////////////////////////
            if ( String.IsNullOrEmpty(Input.Remarks))
            {
                ModelState.AddModelError("ApproverRemarks", "Remarks are required when enrollment request has been denied");

                ////////////////////////////////////////////////////////////////////////////////////////////////
                // Rebuild page 
                ////////////////////////////////////////////////////////////////////////////////////////////////
                ProgramEnrollment = await this.retrieveProgramEnrollment(this.createAuthorizationSQL(), id);
                EnrollmentHistory = await this.retrieveEnrollmentHistory(ProgramEnrollment.ProgramEnrollmentID); 
                ShowReviewForm      = true;
                ShowApproveButton   = true;
                ShowDenyButton      = true;
                ShowRevokeButton    = false;
                return Page();
            }

            return await this.OnPostAsync
            (
                id, 
                StatusCodeConstants.DENIED, 
                TransitionCodeConstants.PENDING_TO_DENIED
            );
        }
        public async Task<IActionResult> OnPostRevokeAsync(int id)
        {
            return await this.OnPostAsync
            (
                id, 
                StatusCodeConstants.REVOKED, 
                TransitionCodeConstants.APPROVED_TO_REVOKED
            );
        }

        public async Task<IActionResult> OnPostAsync(int programEnrollmentID, string statusCode, string statusTransitionCode)
        {
            Console.WriteLine("Approvals.Review.OnPostAsync(): BEGIN");
            Console.WriteLine("id: " + programEnrollmentID);
            Console.WriteLine("Remarks: " + Input.Remarks);

            ////////////////////////////////////////////////////////////
            // Step #1:
            // Check to see if records exists
            ////////////////////////////////////////////////////////////
            var lvProgramEnrollment = await _dbContext.ProgramEnrollments
                                        .Where(pe => pe.ProgramEnrollmentID == programEnrollmentID) 
                                        .AsNoTracking()
                                        .SingleOrDefaultAsync();     

            ////////////////////////////////////////////////////////////
            // Return "Not Found" if record doesn't exist
            ////////////////////////////////////////////////////////////
            if (lvProgramEnrollment == null)
            {
                Console.WriteLine("ProgramEnrollment NOT FOUND in Step #1");
                return NotFound();
            } 

            ////////////////////////////////////////////////////////////
            // Step #2:
            // Now that record exists, make sure that the logged-in user
            // is authorized to edit (approver/deny) enrollment
            // applications for this particular LMS Program.
            ////////////////////////////////////////////////////////////
            var sql = " SELECT * "

lmsextreg/Pages/Approvals/Edit.cshtml
@page "{id:int}"
@model lmsextreg.Pages.Approvals.EditModel

@{
    ViewData["Title"] = "Approvals";
}
<h2>Approve/Deny</h2>
<div>
    <h4>Enrollment Application</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Applicant's Name:</dt>
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.FullName)
        </dd>
        <dt>Email Address:</dt>
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.UserName)
        </dd>
        <dt>Agency:</dt>   
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.Agency.AgencyName)
        </dd>    
        <dt>Sub-Agency:</dt>   
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.SubAgency.SubAgencyName)
        </dd>     
        <dt>Job Title:</dt>   
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.JobTitle)
        </dd>                          
    </dl>   
</div>
<div class="form-group">
    <form style="display:inline;" method="post">
        <input type="hidden" name="id" value="@Model.ProgramEnrollment.ProgramEnrollmentID" />
        <input type="hidden" name="status" value="APPROVED" />
        <button type="submit" class="btn btn-xs btn-success">Approve</button>
    </form>
    <form style="display:inline;" method="post">
        <input type="hidden" name="id" value="@Model.ProgramEnrollment.ProgramEnrollmentID" />
        <input type="hidden" name="status" value="DENIED" />
        <button type="submit" class="btn btn-xs btn-danger">Deny</button>
    </form>
</div>
<div class="form-group">   
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lmsextreg/Pages/Approvals/Index.cshtml
@page
@model lmsextreg.Pages.Approvals.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h3 style="margin-bottom: 2px;">@Model.LoggedInUser.FullName</h3>
<h4 style="margin-top: 2px;">Programs Enrollments</h4>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProgramEnrollment[0].LMSProgram)
            </th>     
            <th>
                @Html.DisplayNameFor(model => model.ProgramEnrollment[0].Student)
            </th>   
           <th>
                @Html.DisplayNameFor(model => model.ProgramEnrollment[0].Student.Agency.AgencyName)
            </th>                              
            <th>
                @Html.DisplayNameFor(model => model.ProgramEnrollment[0].EnrollmentStatus)
            </th>   
            <th>
                @Html.DisplayNameFor(model => model.ProgramEnrollment[0].Approver)
            </th>                                
            <th>
                @Html.DisplayNameFor(model => model.ProgramEnrollment[0].DateCreated)
            </th>
            <th>Available Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ProgramEnrollment) 
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LMSProgram.LongName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.FullName)
                </td>  
                <td>
                    @Html.DisplayFor(modelItem => item.Student.Agency.AgencyName)
                </td>                             
                <td>
                    @Html.DisplayFor(modelItem => item.EnrollmentStatus.StatusLabel)
                </td> 
                <td>
                    @Html.DisplayFor(modelItem => item.Approver.FullName)
                </td>                                    
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    @if ( item.StatusCode == @Model.PENDING)
                    {
                        <a asp-page="./Review"  asp-route-id="@item.ProgramEnrollmentID">Review</a>
                        @(" | ")
                        <a asp-page="./Review"  asp-route-id="@item.ProgramEnrollmentID">Approve/Deny</a>
                    }
                    @if ( item.StatusCode == @Model.APPROVED )
                    {
                        <a asp-page="./Review"  asp-route-id="@item.ProgramEnrollmentID">Review</a>
                        @(" | ")
                        <a asp-page="./Review"  asp-route-id="@item.ProgramEnrollmentID">Revoke</a>
                    }                                         
                    @if ( item.StatusCode == @Model.DENIED)
                    {
                        <a asp-page="./Review"  asp-route-id="@item.ProgramEnrollmentID">Review</a>
                        @(" | ")
                        <a asp-page="./Review"  asp-route-id="@item.ProgramEnrollmentID">Approve</a>
                    }
                    @if ( item.StatusCode == @Model.WITHDRAWN || item.StatusCode == @Model.REVOKED )
                    {
                        <a asp-page="./Review"  asp-route-id="@item.ProgramEnrollmentID">Review</a>
                    }  
                </td>
            </tr>
        }
    </tbody> 
</table>

lmsextreg/Pages/Approvals/Review.cshtml
@page "{id:int}"
@model lmsextreg.Pages.Approvals.ReviewModel

@{
    ViewData["Title"] = "Approvals";
}
<h2>@Html.DisplayFor(model => model.ProgramEnrollment.LMSProgram.LongName)</h2>
<h4>Enrollment Application Details</h4>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>Applicant's Name:</dt>
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.FullName)
        </dd>
        <dt>Email Address:</dt>
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.UserName)
        </dd>
        <dt>Agency:</dt>   
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.Agency.AgencyName)
        </dd>    
        <dt>Sub-Agency:</dt>   
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.SubAgency.SubAgencyName)
        </dd>     
        <dt>Job Title:</dt>   
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.Student.JobTitle)
        </dd>  
        <dt>Program Name:</dt>  
        <dd>
            @Html.DisplayFor(model => model.ProgramEnrollment.LMSProgram.LongName)
        </dd>        
        <dt>Enrollment Status:</dt>   
        <dd>
            <span style="border: 2px solid red;font-weight:bold;">@Html.DisplayFor(model => model.ProgramEnrollment.EnrollmentStatus.StatusLabel)</span>
        </dd>     
        <dt>Enrollment History:</dt>   
        <dd>
            <table class="table table-bordered table-striped table-sm" style="width=50%;">
                <thead>
                    <tr style="color:#FFF;background-color:#A9A9A9">
                        <td>Who</td>
                        <td>What</td>
                        <td>When</td>
                        <td>Remarks</td>
                    </tr> 
                </thead> 
                <tbody>
                    @foreach (var item in Model.EnrollmentHistory) 
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Actor.FullName)</td>
                            <td>@Html.DisplayFor(modelItem => item.StatusTransition.TransitionLabel)</td>                            
                            <td>@Html.DisplayFor(modelItem => item.DateCreated)</td>
                            <td>@Html.DisplayFor(modelItem => item.ActorRemarks)</td> 
                        </tr>
                    }                    
                </tbody>
            </table>      
        </dd>                                       
    </dl>   
</div>
@if ( @Model.ShowReviewForm )
{
    <form method="post">
        <input type="hidden" name="id" value="@Model.ProgramEnrollment.ProgramEnrollmentID" />
       <div class="input-group mb3">
             <div class="form-group">
                <label asp-for="Input.Remarks"></label>:
                <div asp-validation-summary="All" class="text-danger"></div>
                <textarea asp-for="Input.Remarks" id="ApproverRemarks" class="form-control" style="margin-top:0px;" rows="3" cols="40"></textarea>
            </div>
            <div class="form-group">
                @if ( @Model.ShowApproveButton )
                {
                    <input type="submit" class="btn btn-xs btn-success" style="margin-top: 10px;" asp-page-handler="Approve" value="Approve" />
                }
                @if ( @Model.ShowDenyButton )
                {
                    <input type="submit" class="btn btn-xs btn-danger" style="margin-top: 10px;" asp-page-handler="Deny" value="Deny" />
                }
                @if ( @Model.ShowRevokeButton )
                {
                    <input type="submit" class="btn btn-xs btn-danger" style="margin-top: 10px;" asp-page-handler="Revoke" value="Revoke" />
                }
            </div>
       </div>  
    </form>
}
<div class="form-group">   
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}